moon:
  enabled: true
  rebalance_frequency: monthly
  strategies:
    - ADM
    - BAA
    - BDA
    - HAA
    - VAA
  strategy_weighting: equal
  execution_mode: consensus
  signal_assets:
    enabled: true
  execution_mapping:
    enabled: true
